Downgraded codebase to Java 11
coveo/push-api-client.java pull request #19
Opened 2022-02-15 05:33 UTC by brianlangeland

Downgraded codebase to Java 11 by mostly converting 'record' classes into standard 'class' classes and changing the pom's source/target to 11. Also added to the gitignore.

2022-02-16 15:03 UTC, louis-bompart requested changes
Thanks for that PR @brianlangeland.
To be perfectly equivalent feature-wise, there are a few things missing.
For each records, the classes should meet the following:
1. `private`, `final` field for each piece of data - here the `final` keywords are missing.
2. getter for each field.
3. `public` constructor with a corresponding argument for each field
4. `equals` method that returns true for objects of the same class when all fields match
5. `hashCode` method that returns the same value when all fields match
6. `toString` method that includes the name of the class and the name of each field and its corresponding value

Indeed, to avoid a breaking change, we ought to ensure that the code is strictly behaving as before, and that includes the methods that were automatically generated and the immutable aspect of the fields.

Reference: https://www.baeldung.com/java-record-keyword 

I don't know if the generated `hashCode`, `toString` and `equals` will behave the same depending on if it's a class or a record?

I'd advise you to have the classes you propose side-by-side with the records that you remove, and test them together:
 - [ ] Ensure `SomeRecordInstance.toString() == `YourClassThatReplaceThatRecord.toString()`
 - [ ] Ensure `SomeRecordInstance.hashCode() == `YourClassThatReplaceThatRecord.hashCode()`
 - [ ] Ensure `SomeRecordInstance.equals(AnotherRecordInstance) == YourClassThatReplaceThatRecord.equals(AnotherClassInstance)`
 
For each one, I'd advise you to do multiple tests and to verify all the aspects of the contract of those methods, as defined in [the JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html).

For example, ensure that your override of the `equals` method is reflexive, symmetric, transitive, consistent and that "For any non-null reference value x, x.equals(null) should return false."

2022-03-17 22:48 UTC, brianlangeland commented
I used IntelliJ to generate the hashCode, toString, and equals methods in the Class versions, and then ran a number of tests against them. Along with that, I wrote test cases to test numerous different variations of the objects and ensured that all of them pass in both the Record and Class versions.

The generated methods for toString and hashCode from the classes behave extremely similarly to those of the implied methods of the records. For example, here is the output of SecurityIdentityBatchConfig's toString methods:

Record: SecurityIdentityBatchConfig[fileId=some_file_id, orderingId=123]
Class : SecurityIdentityBatchConfig[fileId='some_file_id', orderingId=123]

The output of these two implementations is nearly identical (with just the class implementation adding single quotes around the String's value). The toString from BatchUpdate takes the List and DocumentBuilder objects and outputs those in an identical manor (using the object's classpath and runtime info):

Record: BatchUpdate[addOrUpdate=[com.coveo.pushapiclient.DocumentBuilder@9e89d68, com.coveo.pushapiclient.DocumentBuilder@3b192d32], delete=[com.coveo.pushapiclient.DocumentBuilder@9e89d68, com.coveo.pushapiclient.DocumentBuilder@16f65612]]

Class : BatchUpdate[addOrUpdate=[com.coveo.pushapiclient.DocumentBuilder@46daef40, com.coveo.pushapiclient.DocumentBuilder@12f41634], delete=[com.coveo.pushapiclient.DocumentBuilder@46daef40, com.coveo.pushapiclient.DocumentBuilder@13c27452]]

For hashCode, I see very similar results as well. In GroupSecurityIdentityBuilder, pushing in identical values into both the class and record objects results in the following:

Record: -1806899415
Class : -2065696871

My assumption is that the difference is that the Record hashCode implementation is using a different multiplier to generate the actual hash.

In terms of the actual functionality, they end up functioning identically. All of the unit tests pass regardless of whether they are run against Records or Classes.

2022-03-18 01:22 UTC, louis-bompart approved these changes

2022-03-18 20:12 UTC, brianlangeland commented
Updated to 2.0.0

2022-03-21 18:02 UTC, olamothe approved these changes

2022-03-21 18:02 UTC, merged